### ISSUE TITLE
Random Issue with Random Number

### ISSUE THREAD

**Issue by Matt-Sredojevic** [tristanhustrulid/Hustrulid_CSCI2270_FinalProject#1]
When working with the guess a number between 1 and 10, there was a one off issue with the game.  The first time i ended up playing the game, it gave me an issue where i guessed 2 and it said too high. I then guessed 1 and it said two low.  I began to guess numbers between 2 and 1 but it was stuck.  In an attempt to recreate this, it never occurred.

**Comment by tristanhustrulid** [comment]
Hey Matt,
     I was unable to recreate the issue, every time has worked for me.
Thank you for your input. I tried to reply on github, yet there was no
option to do so. Thanks again, if this error reoccurs for me I will try and
fix the issue.

-Tristan Hustrulid
